# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee4d5ff7aa4c6179908d66fa1eaad997a3545ace4dfd94705f2e9ef8133654c50ec4b214348a32def0bd35b5939c70c893b015a0956ee6394575105e0ae6667

test:
  secret_key_base: 9a71128451a47feed2df913988b213ca53957759d31becd19be96a7c59c98cbec83319a857e168f7d263282caa4f5334c1b5edd46d9dc00c752b18a2fb7f7858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
